# Notebook params

In [4]:
CREATE_TOKENIZER = True

# BPE Tokenizer

In [8]:
if CREATE_TOKENIZER:
    from utils import filter_words
    from Tokenizers import train_bpe_tokenizer
    filter_words("data/dict.txt", "data/cleared_dict.txt")
    train_bpe_tokenizer("data/cleared_dict.txt", vocab_size=28,
                        save_path="models/cleared_tokenizer_bpe.json")


Saved trained BPE tokenizer to models/cleared_tokenizer_bpe.json


In [20]:
from Tokenizers import load_tokenizer, train_bpe_tokenizer
t = load_tokenizer("models/cleared_tokenizer_bpe.json")
t.get_vocab()

{'f': 8,
 'n': 16,
 'e': 7,
 'j': 12,
 'm': 15,
 'l': 14,
 'a': 3,
 'z': 28,
 'c': 5,
 's': 21,
 'h': 10,
 'w': 25,
 '[MASK]': 2,
 'r': 20,
 't': 22,
 'q': 19,
 'o': 17,
 'p': 18,
 'g': 9,
 'u': 23,
 'v': 24,
 'b': 4,
 'k': 13,
 '[PAD]': 0,
 'i': 11,
 'x': 26,
 'y': 27,
 'd': 6,
 '[UNK]': 1}

In [28]:
torch.randint(0, 12, [1,2])

tensor([[9, 5]])

In [25]:
t.decode([2] , skip_special_tokens=False)

'[MASK]'

# Models

In [ ]:
!python main.py --words_file data/cleared_dict.txt --out_dir out --tokenizer_path models/cleared_tokenizer_bpe.json

In [1]:
import numpy as np

In [1]:
import torch

In [2]:
from torch import nn

In [3]:
loss = nn.CrossEntropyLoss()

In [50]:
logits = torch.randn([10,2,2])

In [47]:
logits.shape

torch.Size([10, 2, 2])

In [48]:
logits[0][0]

tensor([-0.0207, -0.0716])

In [51]:
target = [[[1]],[[1]], [[1]]]

In [39]:
target[0][0]

[1, 0]

In [52]:
target = torch.Tensor(target)

In [54]:
target.shape

torch.Size([3, 1, 1])

In [53]:
loss(logits,target)

RuntimeError: Expected target size [3, 2], got [3, 1, 1]

In [23]:
loss(torch.tensor([[0.5,0.5],[0.5,0.5],[0.5,0.5],[0.5,0.5]]),torch.Tensor([[1,1][1,1]]))

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Temp\ipykernel_16392\571207724.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  loss(torch.tensor([[0.5,0.5],[0.5,0.5],[0.5,0.5],[0.5,0.5]]),torch.Tensor([[1,1][1,1]]))


TypeError: list indices must be integers or slices, not tuple

In [15]:
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[1,2,3],[4,5,7]])

In [18]:
torch.all(a == b, dim = 1)

tensor([ True, False])

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [9]:
np.all(a > 3 == a <3)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()